apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: nvidia-llama-3-1-8b-awq-nvidia
  annotations:
    scenarios.ai.sap.com/description: "Run vLLM server with official Meta Llama 3.1 8B AWQ on T4"
    scenarios.ai.sap.com/name: "nvidia-llama-3-1-8b-awq-nvidia"
    executables.ai.sap.com/description: "Llama 3.1 8B Instruct AWQ"
    executables.ai.sap.com/name: "nvidia-llama-3-1-8b-awq-nvidia"
  labels:
    scenarios.ai.sap.com/id: "nvidia-llama-3-1-8b-awq-nvidia"
    ai.sap.com/version: "0.0.1"
spec:
  inputs:
    parameters:
      - name: modelName
        default: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4" 
        type: string
      - name: dataType
        default: "half" 
        type: string
      - name: gpuMemoryUtilization
        default: "0.85" # Slight reduction to leave room for T4's small VRAM
        type: string
      - name: maxTokenLen
        default: "4096" 
        type: string
      - name: maxNumBatchedTokens
        default: "512" 
        type: string
      - name: maxNumSeqs
        default: "16" 
        type: string
      - name: quantization
        default: "awq" # Changed from compressed-tensors to awq
        type: string
      - name: resourcePlan
        type: "string"
        default: "infer.l"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/vllm-nvidia:25.12.post1
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: VLLM_NO_DEPRECATION_WARNING
              value: "1"
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "-------------Starting vLLM OpenAI API Server--------------" 
              && python3 -m vllm.entrypoints.openai.api_server 
              --model {{inputs.parameters.modelName}}
              --dtype {{inputs.parameters.dataType}}
              --gpu-memory-utilization {{inputs.parameters.gpuMemoryUtilization}}
              --max-model-len {{inputs.parameters.maxTokenLen}}
              --max-num-batched-tokens {{inputs.parameters.maxNumBatchedTokens}}
              --max-num-seqs {{inputs.parameters.maxNumSeqs}}
              --quantization {{inputs.parameters.quantization}}
              --enable-chunked-prefill
