apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: shimmy-rbac-fix
  annotations:
    scenarios.ai.sap.com/description: "Shimmy with Istio bypass - no RBAC enforcement"
    scenarios.ai.sap.com/name: "shimmy-rbac-fix"
    executables.ai.sap.com/description: "Shimmy inference service with Istio port exclusion to bypass RBAC"
    executables.ai.sap.com/name: "shimmy-rbac-fix"
  labels:
    scenarios.ai.sap.com/id: "shimmy-rbac-fix"
    ai.sap.com/version: "1.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
        sidecar.istio.io/rewriteAppHTTPProbers: true
        traffic.sidecar.istio.io/excludeInboundPorts: 8080
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/shimmy:latest
          ports:
          - containerPort: 8080
            protocol: TCP
