apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: shimmy-gemma-2b
  annotations:
    scenarios.ai.sap.com/description: "Run Shimmy inference server with Gemma-2B-IT model on SAP AI Core"
    scenarios.ai.sap.com/name: "shimmy-gemma-2b"
    executables.ai.sap.com/description: "Shimmy inference service with baked-in Gemma-2B-IT Q4_K_M model"
    executables.ai.sap.com/name: "shimmy-inference"
  labels:
    scenarios.ai.sap.com/id: "shimmy-inference"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.m
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 3
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/shimmy:latest
          ports:
          - containerPort: 8000
            name: http1
            protocol: TCP
          env:
            - name: SHIMMY_PORT
              value: "8080"
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
              nvidia.com/gpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4000m"
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
