apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: mistral-7b-trt-t4
  annotations:
    scenarios.ai.sap.com/description: "Mistral 7B Optimized for T4 via TensorRT-LLM"
    scenarios.ai.sap.com/name: "mistral-7b-trt-t4"
    executables.ai.sap.com/description: "TensorRT-LLM optimized inference for Mistral 7B AWQ"
    executables.ai.sap.com/name: "mistral-7b-trt-t4"
  labels:
    scenarios.ai.sap.com/id: "mistral-7b-trt-t4"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: modelName
        default: "solidrust/Mistral-7B-Instruct-v0.3-AWQ"
        type: string
      - name: maxContext
        default: "8192"
        type: string
      - name: maxBatchSize
        default: "8"
        type: string
      - name: resourcePlan
        type: "string"
        default: "infer.l"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/mistral-trt-t4:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: MODEL
              value: "{{inputs.parameters.modelName}}"
            - name: MAX_CONTEXT
              value: "{{inputs.parameters.maxContext}}"
            - name: MAX_BATCH_SIZE
              value: "{{inputs.parameters.maxBatchSize}}"
